### ISSUE TITLE
Week #4 Ready for Review 

### ISSUE THREAD

**Issue by amgenz15** [amgenz15/foodieGrubProject#2]
@pawaitemadisoncollege week 4 is complete! 

1. My key takeaway is to ensure that when you annotate for hibernate, ensure everything aligns with your created database. I spent way too long on an SQL error thrown by this lol. Hibernate is also super useful and is a huge help to not have to continuously code the same things all the time, especially when working with applications that are connected to a database. 
2.  I ran into an SQLGrammerException and I figured out that it was pointing to my JavaBean because I did the hibernate annotations wrong. After some research, I ended up figuring out it was indeed my annotations. 
3. To solve my issue in #2, I ended up finding an article on stack overflow, https://stackoverflow.com/questions/34446364/org-hibernate-exception-sqlgrammarexception-could-not-extract-resultset to help me figure out where my error could potentially be.

**Comment by pawaitemadisoncollege** [comment]
Hi @amgenz15 Yes! Those details can really get you, can't they? So much of our time as developers is spent chasing down a missed detail - but you'll get faster at it as you solve more and more of them. I don't know that we can prevent those mini-mistakes, but we can improve the time to solve them!

You have a good start here with Hibernate, and implementing it directly in your project will save you some time down the road!

- [x] I noticed that sneaky ${filepath} directory issue in your repository - check out my post from earlier today in Slack to help resolve it. If that doesn't work, let me know.
- [x] Verifying the entities are saved/updated/inserted correctly can be more thorough by implementing and using equals() on each entity - refer to the video Comparing Hibernate Entities with equals in week 5 for more detail.  An example of using that equals method in a unit test would be something like `assertTrue(expectedUser.equals(actualUser));` so that you don't have to compare each instance var/column manually like this: https://github.com/amgenz15/foodieGrubProject/blob/806559e8504e1db2e652fa69e8918d601c9f649b/src/test/java/com/amgenz/persistence/UserDaoTest.java#L58

On to more practice with Hibernate in week 5!
